image: ubuntu:latest

stages:
  - test

test:
  stage: test
  before_script:
    - apt update
    - apt install -y python3.11 python3-pip
    - python3.11 -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests.py --cov=./
    - coverage html
  artifacts:
    paths:
      - htmlcov/*
  tags:
    - common
    - cpu
