name: test_parsers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: apt update && apt install -y python3.11 python3-pip && python3.11 -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Test
        run: pytest tests.py --cov=./ && coverage html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov/*
